language: node_js

node_js:
    - 16.1.0

cache:
    npm: false
    directories:
        - "~/.pnpm-store"

before_install:
    - curl -L https://unpkg.com/@pnpm/self-installer | node
    - pnpm config set store-dir ~/.pnpm-store

script:
    - pnpm ci
