language: node_js

node_js:
    - 16.5.0

cache:
    npm: false
    directories:
        - "~/.pnpm-store"

before_install:
    - npm i -g pnpm
    - pnpm config set store-dir ~/.pnpm-store

install:
    - pnpm i

script:
    - pnpm ci
