dist: focal

language: node_js

node_js:
    - 18.17.1

cache:
    npm: false
    directories:
        - ~/.pnpm-store

before_install:
    - npm add -g pnpm@8
    - pnpm config set store-dir ~/.pnpm-store

install:
    - pnpm i

script:
    - pnpm run ci
