export default {
    "accessor-pairs": 2,
    "array-callback-return": [2, { allowImplicit: true, checkForEach: true }],
    "arrow-body-style": 2,
    "block-scoped-var": 0,
    camelcase: [2, { properties: "never" }],
    "capitalized-comments": 0,
    "class-methods-use-this": 0,
    complexity: 0,
    "consistent-return": 0,
    "consistent-this": 0,
    "constructor-super": 2,
    curly: 2,
    "default-case": 0,
    "default-case-last": 2,
    "default-param-last": 2,
    "dot-notation": 2,
    eqeqeq: 2,
    "for-direction": 2,
    "func-name-matching": 0,
    "func-names": [2, "never"],
    "func-style": [2, "declaration", { allowArrowFunctions: true }],
    "getter-return": [2, { allowImplicit: true }],
    "grouped-accessor-pairs": [2, "getBeforeSet"],
    "guard-for-in": 2,
    "id-denylist": 0,
    "id-length": 0,
    "id-match": 0,
    "init-declarations": 0,
    "logical-assignment-operators": [2, "always", { enforceForIfStatements: true }],
    "max-classes-per-file": 0,
    "max-depth": 0,
    "max-lines": 0,
    "max-lines-per-function": 0,
    "max-nested-callbacks": 0,
    "max-params": 0,
    "max-statements": 0,
    "new-cap": 2,
    "no-alert": 2,
    "no-array-constructor": 2,
    "no-async-promise-executor": 2,
    "no-await-in-loop": 0,
    "no-bitwise": 2,
    "no-caller": 2,
    "no-case-declarations": 2,
    "no-class-assign": 2,
    "no-compare-neg-zero": 2,
    "no-cond-assign": [2, "always"],
    "no-console": 0,
    "no-const-assign": 2,
    "no-constant-binary-expression": 2,
    "no-constant-condition": [2, { checkLoops: false }],
    "no-constructor-return": 2,
    "no-continue": 0,
    "no-control-regex": 2,
    "no-debugger": 2,
    "no-delete-var": 2,
    "no-div-regex": 2,
    "no-dupe-args": 2,
    "no-dupe-class-members": 2,
    "no-dupe-else-if": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-duplicate-imports": [2, { includeExports: true }],
    "no-else-return": 0,
    "no-empty": [2, { allowEmptyCatch: true }],
    "no-empty-character-class": 2,
    "no-empty-function": 0,
    "no-empty-pattern": 2,
    "no-empty-static-block": 2,
    "no-eq-null": 0,
    "no-eval": 2,
    "no-ex-assign": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-boolean-cast": [2, { enforceForLogicalOperands: true }],
    "no-extra-label": 0,
    "no-fallthrough": 2,
    "no-func-assign": 2,
    "no-global-assign": 2,
    "no-implicit-coercion": 0,
    "no-implicit-globals": 0,
    "no-implied-eval": 2,
    "no-import-assign": 2,
    "no-inline-comments": 0,
    "no-inner-declarations": 0,
    "no-invalid-regexp": 2,
    "no-invalid-this": 2,
    "no-irregular-whitespace": 2,
    "no-iterator": 2,
    "no-label-var": 0,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-lonely-if": 0,
    "no-loop-func": 2,
    "no-loss-of-precision": 2,
    "no-magic-numbers": 0,
    "no-misleading-character-class": 2,
    "no-multi-assign": 2,
    "no-multi-str": 2,
    "no-negated-condition": 2,
    "no-nested-ternary": 2,
    "no-new": 2,
    "no-new-func": 2,
    "no-new-native-nonconstructor": 2,
    "no-new-wrappers": 2,
    "no-nonoctal-decimal-escape": 2,
    "no-obj-calls": 2,
    "no-object-constructor": 2,
    "no-octal": 2,
    "no-octal-escape": 2,
    "no-param-reassign": 2,
    "no-plusplus": 0,
    "no-promise-executor-return": 2,
    "no-proto": 2,
    "no-prototype-builtins": 2,
    "no-redeclare": 0,
    "no-regex-spaces": 2,
    "no-restricted-exports": 0,
    "no-restricted-globals": 0,
    "no-restricted-imports": 0,
    "no-restricted-properties": 0,
    "no-restricted-syntax": 0,
    "no-return-assign": 2,
    "no-script-url": 2,
    "no-self-assign": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-setter-return": 2,
    "no-shadow": [
        2,
        {
            builtinGlobals: true,
            hoist: "never",
            allow: ["name", "status", "length", "open", "close"]
        }
    ],
    "no-shadow-restricted-names": 2,
    "no-sparse-arrays": 2,
    "no-template-curly-in-string": 2,
    "no-ternary": 0,
    "no-this-before-super": 2,
    "no-throw-literal": 2,
    "no-undef": [2, { typeof: true }],
    "no-undef-init": 2,
    "no-undefined": 0,
    "no-underscore-dangle": [2, { allowAfterThis: true, allowFunctionParams: false }],
    "no-unexpected-multiline": 2,
    "no-unmodified-loop-condition": 2,
    "no-unneeded-ternary": 2,
    "no-unreachable": 2,
    "no-unreachable-loop": 2,
    "no-unsafe-finally": 2,
    "no-unsafe-negation": [2, { enforceForOrderingRelations: true }],
    "no-unsafe-optional-chaining": [2, { disallowArithmeticOperators: true }],
    "no-unused-expressions": 2,
    "no-unused-labels": 0,
    "no-unused-private-class-members": 2,
    "no-unused-vars": [2, { ignoreRestSiblings: true, caughtErrors: "all" }],
    "no-use-before-define": 2,
    "no-useless-assignment": 2,
    "no-useless-backreference": 2,
    "no-useless-call": 2,
    "no-useless-catch": 2,
    "no-useless-computed-key": [2, { enforceForClassMembers: true }],
    "no-useless-concat": 2,
    "no-useless-constructor": 2,
    "no-useless-escape": 2,
    "no-useless-rename": 2,
    "no-useless-return": 2,
    "no-var": 2,
    "no-void": 2,
    "no-warning-comments": 2,
    "no-with": 2,
    "object-shorthand": [2, "always", { avoidExplicitReturnArrows: true }],
    "one-var": [2, "never"],
    "operator-assignment": 2,
    "prefer-arrow-callback": 2,
    "prefer-const": [2, { destructuring: "all" }],
    "prefer-destructuring": [
        2,
        {
            VariableDeclarator: { object: true, array: false },
            AssignmentExpression: { object: false, array: false }
        }
    ],
    "prefer-exponentiation-operator": 2,
    "prefer-named-capture-group": 0,
    "prefer-numeric-literals": 2,
    "prefer-object-has-own": 2,
    "prefer-object-spread": 2,
    "prefer-promise-reject-errors": 2,
    "prefer-regex-literals": [2, { disallowRedundantWrapping: true }],
    "prefer-rest-params": 2,
    "prefer-spread": 2,
    "prefer-template": 2,
    radix: [2, "as-needed"],
    "require-atomic-updates": 0,
    "require-await": 0,
    "require-unicode-regexp": 0,
    "require-yield": 2,
    "sort-imports": 0,
    "sort-keys": 0,
    "sort-vars": 0,
    strict: 2,
    "symbol-description": 2,
    "unicode-bom": 2,
    "use-isnan": [2, { enforceForIndexOf: true }],
    "valid-typeof": [2, { requireStringLiterals: true }],
    "vars-on-top": 0,
    yoda: [2, "never", { exceptRange: true }]
}
