module.exports = {
    rules: {
        /*
            Possible errors
        */
        "color-no-invalid-hex": true,
        "font-family-no-duplicate-names": true,
        "font-family-no-missing-generic-family-keyword": true,
        "named-grid-areas-no-invalid": true,
        "function-calc-no-invalid": true,
        "function-calc-no-unspaced-operator": true,
        "function-linear-gradient-no-nonstandard-direction": true,
        "string-no-newline": true,
        "unit-no-unknown": true,
        "property-no-unknown": true,
        "keyframe-declaration-no-important": true,
        "declaration-block-no-duplicate-custom-properties": true,
        "declaration-block-no-duplicate-properties": true,
        "declaration-block-no-shorthand-property-overrides": true,
        "block-no-empty": true,
        "selector-pseudo-class-no-unknown": true,
        "selector-pseudo-element-no-unknown": true,
        "selector-type-no-unknown": true,
        "media-feature-name-no-unknown": true,
        "at-rule-no-unknown": true,
        "comment-no-empty": true,
        "no-descending-specificity": true,
        "no-duplicate-at-import-rules": true,
        "no-duplicate-selectors": [true, { disallowInList: true }],
        "no-empty-source": true,
        "no-extra-semicolons": true,
        "no-invalid-double-slash-comments": true,
        "no-invalid-position-at-import-rule": true,

        /*
            Limit language features
        */
        "alpha-value-notation": "number",
        "hue-degree-notation": "angle",
        "color-function-notation": "modern",
        "color-named": "never",
        // "color-no-hex": true,
        "length-zero-no-unit": true,
        "font-weight-notation": "named-where-possible",
        // "function-allowed-list": [],
        // "function-disallowed-list": [],
        "function-url-no-scheme-relative": true,
        "function-url-scheme-allowed-list": ["data", "/^http/"],
        // "function-url-scheme-disallowed-list": [],
        // "keyframes-name-pattern": "",
        "number-max-precision": 2,
        // "time-min-milliseconds": 100,
        // "unit-allowed-list": [],
        // "unit-disallowed-list": [],
        "shorthand-property-no-redundant-values": true,
        "value-no-vendor-prefix": true,
        // "custom-property-pattern": "",
        // "property-allowed-list": [],
        // "property-disallowed-list": [],
        "property-no-vendor-prefix": true,
        "declaration-block-no-redundant-longhand-properties": true,
        // "declaration-no-important": true,
        // "declaration-property-unit-allowed-list": [],
        // "declaration-property-unit-disallowed-list": [],
        // "declaration-property-value-allowed-list": [],
        // "declaration-property-value-disallowed-list": [],
        "declaration-block-single-line-max-declarations": 1,
        // "selector-attribute-name-disallowed-list": [],
        // "selector-attribute-operator-allowed-list": [],
        // "selector-attribute-operator-disallowed-list": [],
        // "selector-class-pattern": "",
        // "selector-combinator-allowed-list": [],
        // "selector-combinator-disallowed-list": [],
        // "selector-id-pattern": [],
        // "selector-max-attribute": 2,
        // "selector-max-class": 2,
        // "selector-max-combinators": 2,
        // "selector-max-compound-selectors": 3,
        "selector-max-empty-lines": 0,
        // "selector-max-id": 2,
        // "selector-max-pseudo-class": 1,
        // "selector-max-specificity": "0,2,0",
        // "selector-max-type": 2,
        // "selector-max-universal": 2,
        // "selector-nested-pattern": "",
        // "selector-no-qualifying-type": true,
        "selector-no-vendor-prefix": true,
        // "selector-pseudo-class-allowed-list": [],
        // "selector-pseudo-class-disallowed-list": [],
        // "selector-pseudo-element-allowed-list": [],
        "selector-pseudo-element-colon-notation": "double",
        // "selector-pseudo-element-disallowed-list": [],
        // "media-feature-name-allowed-list": [],
        // "media-feature-name-disallowed-list": [],
        "media-feature-name-no-vendor-prefix": true,
        // "media-feature-name-value-allowed-list": [],
        // "custom-media-pattern": "",
        // "at-rule-allowed-list": [],
        // "at-rule-disallowed-list": [],
        "at-rule-no-vendor-prefix": true,
        // "at-rule-property-requirelist": [],
        // "comment-pattern": "",
        // "comment-word-disallowed-list": [],
        // "max-nesting-depth": 2,
        "no-unknown-animations": true,

        /*
            Stylistic issues
        */
        "color-hex-case": "lower",
        "color-hex-length": "short",
        "font-family-name-quotes": "always-unless-keyword",
        "function-comma-newline-after": "always-multi-line",
        "function-comma-newline-before": "never-multi-line",
        "function-comma-space-after": "always-single-line",
        "function-comma-space-before": "never",
        "function-max-empty-lines": 0,
        "function-name-case": "lower",
        "function-parentheses-newline-inside": "always-multi-line",
        "function-parentheses-space-inside": "never",
        "function-url-quotes": "always",
        "function-whitespace-after": "always",
        "number-leading-zero": "always",
        "number-no-trailing-zeros": true,
        "string-quotes": ["double", { avoidEscape: false }],
        "unit-case": "lower",
        "value-keyword-case": "lower",
        "value-list-comma-newline-after": "always-multi-line",
        "value-list-comma-newline-before": "never-multi-line",
        "value-list-comma-space-after": "always-single-line",
        "value-list-comma-space-before": "never",
        "value-list-max-empty-lines": 0,
        "custom-property-empty-line-before": "never",
        "property-case": "lower",
        "declaration-bang-space-after": "never",
        "declaration-bang-space-before": "always",
        "declaration-colon-newline-after": "always-multi-line",
        "declaration-colon-space-after": "always-single-line",
        "declaration-colon-space-before": "never",
        "declaration-empty-line-before": "never",
        "declaration-block-semicolon-newline-after": "always",
        "declaration-block-semicolon-newline-before": "never-multi-line",
        "declaration-block-semicolon-space-after": "always-single-line",
        "declaration-block-semicolon-space-before": "never",
        "declaration-block-trailing-semicolon": "always",
        "block-closing-brace-empty-line-before": "never",
        "block-closing-brace-newline-after": "always",
        "block-closing-brace-newline-before": "always",
        // "block-closing-brace-space-after": "never",
        "block-closing-brace-space-before": "always-single-line",
        "block-opening-brace-newline-after": "always",
        "block-opening-brace-newline-before": "never-single-line",
        "block-opening-brace-space-after": "always-single-line",
        "block-opening-brace-space-before": "always",
        "selector-attribute-brackets-space-inside": "never",
        "selector-attribute-operator-space-after": "never",
        "selector-attribute-operator-space-before": "never",
        "selector-attribute-quotes": "always",
        "selector-combinator-space-after": "always",
        "selector-combinator-space-before": "always",
        "selector-descendant-combinator-no-non-space": true,
        "selector-pseudo-class-case": "lower",
        "selector-pseudo-class-parentheses-space-inside": "never",
        "selector-pseudo-element-case": "lower",
        "selector-type-case": "lower",
        "selector-list-comma-newline-after": "always-multi-line",
        "selector-list-comma-newline-before": "never-multi-line",
        "selector-list-comma-space-after": "always-single-line",
        "selector-list-comma-space-before": "never",
        "rule-empty-line-before": ["always", { ignore: ["inside-block"] }],
        "media-feature-colon-space-after": "always",
        "media-feature-colon-space-before": "never",
        "media-feature-name-case": "lower",
        "media-feature-parentheses-space-inside": "never",
        "media-feature-range-operator-space-after": "always",
        "media-feature-range-operator-space-before": "always",
        "media-query-list-comma-newline-after": "never-multi-line",
        "media-query-list-comma-newline-before": "never-multi-line",
        "media-query-list-comma-space-after": "always-single-line",
        "media-query-list-comma-space-before": "never",
        "at-rule-empty-line-before": ["always", { ignore: "after-comment" }],
        "at-rule-name-case": "lower",
        "at-rule-name-newline-after": "always-multi-line",
        "at-rule-name-space-after": "always-single-line",
        "at-rule-semicolon-newline-after": "always",
        "at-rule-semicolon-space-before": "never",
        "comment-empty-line-before": "always",
        "comment-whitespace-inside": "always",
        indentation: [4, { baseIndentLevel: 1 }],
        linebreaks: "unix",
        "max-empty-lines": 1,
        "max-line-length": 100,
        "no-eol-whitespace": true,
        "no-missing-end-of-source-newline": true,
        "no-empty-first-line": true,
        "unicode-bom": "never",
        "no-irregular-whitespace": true
    }
}
